name: audio_to_sign_language
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.4
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_sound: ^9.28.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^6.3.0
  http: ^1.3.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  rflutter_alert: ^2.0.7
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
#--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/profile/
    - assets/images/learning_section/
    - assets/videos/
    - assets/videos/letters/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800